version: '3.4'

services:

  offersdb:
     container_name: "offersdb"
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
      - 1432:1433
     environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=offersdbpwd123@

  offersbasedb:
     container_name: "offersbasedb"
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
      - 1431:1433
     environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=offersbasedbpwd123@

  offersandusersdatabasemigratorservice:
   container_name: offersandusersdatabasemigratorservice
   image: ${DOCKER_REGISTRY-}offersandusersdatabasemigratorservice
   restart: on-failure
   build : 
    context: .
    dockerfile: OffersAndUsersDatabaseMigratorService/Dockerfile
   depends_on : 
     - offersdb
   entrypoint: ["/app/wait-for-it.sh" , "-t" , "30" , "-h" , "host.docker.internal" , "-p" , "1432", "--" , "dotnet" , "OffersAndUsersDatabaseMigratorService.dll"]
   environment:
    - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1432;Database=Offers;User ID = sa;Password=offersdbpwd123@;TrustServerCertificate=true

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: on-failure:3
    ports:
     - 5672:5672
     - 15672:15672
    environment:
     - RABBITMQ_DEFAULT_USER=RabbitUser
     - RABBITMQ_DEFAULT_PASS=RabbitPassword
    healthcheck:
     test: rabbitmq-diagnostics -q ping
     interval: 30s
     timeout: 30s
     retries: 3

  selenium:
    container_name: "selenium"
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=10800
      - SE_SESSION_REQUEST_TIMEOUT=10800
      - SE_NODE_MAX_SESSIONS=10
    volumes:
      - /dev/shm:/dev/shm

  joboffersservice:
    container_name: "joboffersservice"
    image: ${DOCKER_REGISTRY-}joboffersservice
    restart: on-failure:3
    build:
      context: .
      dockerfile: JobOfferService/Dockerfile 
    ports:
     - 7206:80 
    depends_on:
      rabbitmq:
       condition: service_healthy
      offersdb:
       condition: service_started
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://*:80
     - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672
     - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1432;Initial Catalog=Offers;User ID = sa;Password=offersdbpwd123@;TrustServerCertificate=true

  webscrapperservice:
    container_name: "webscrapperservice"
    image: ${DOCKER_REGISTRY-}webscrapperservice
    restart: on-failure
    build:
        context: .
        dockerfile: WebScrapper/Dockerfile
    depends_on:
      rabbitmq:
       condition: service_healthy
      selenium:
       condition: service_started
    environment:
      - IsSeleniumOnDocker=true
      - RemoteDriverUri=http://host.docker.internal:4444/wd/hub
      - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672

  joboffersmapperserivce:
    container_name: "joboffersmapperservice"
    image: ${DOCKER_REGISTRY}joboffersmapperservice
    restart: on-failure:3
    build:
        context: .
        dockerfile: JobOffersMapperService/Dockerfile
    depends_on:
     rabbitmq:
      condition: service_healthy
     offersbasedb:
      condition: service_started
    environment:
    - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672
    - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1431;Initial Catalog=OffersBase;User ID = sa;Password=offersbasedbpwd123@;TrustServerCertificate=true

  usersservice:
    container_name: usersservice
    image: ${DOCKER_REGISTRY-}usersservice
    restart: on-failure:3
    build:
     context: .
     dockerfile: UsersService/Dockerfile
    ports:
      - 7104:80
    depends_on:
      rabbitmq:
        condition: service_healthy
      offersdb:
        condition: service_started
    environment:
     - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672
     - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1432;Initial Catalog=Offers;User ID = sa;Password=offersdbpwd123@;TrustServerCertificate=true
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://*:80
     - TokenUri=https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=YOURAPIKEYHERE
     - RefreshUri=https://securetoken.googleapis.com/v1/token?key=YOURAPIKEYHERE
     - Audience=YOURAPPNAMEHERE
     - ValidIssuer=https://securetoken.google.com/YOURAPPNAMEHERE



  mailsendingservice:
    container_name: mailsendingservice
    image: ${DOCKER_REGISTRY-}mailsendingservice
    restart: on-failure:3
    build : 
      context: .
      dockerfile: MailSedningService/Dockerfile
    depends_on : 
     rabbitmq:
       condition: service_healthy
    environment : 
     - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672
     - sendingEmail=YOURSENDINGMAIL
     - smtpServer=YOURSMTPSERVER
     - smtpPort=YOURSMTPPORT
     - smtpLogin=YOURSMTPLOGIN
     - smtpPassword=YOURSMTPPASSWORD
