version: '3.4'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: on-failure:3
    ports:
     - 5672:5672
     - 15672:15672
    environment:
     - RABBITMQ_DEFAULT_USER=RabbitUser
     - RABBITMQ_DEFAULT_PASS=RabbitPassword

  joboffersservice:
    container_name: "joboffersservice"
    image: ${DOCKER_REGISTRY-}joboffersservice
    restart: on-failure:always
    build:
      context: .
      dockerfile: JobOfferService/Dockerfile 
    ports:
     - 7206:80 
    depends_on:
     - rabbitmq
    environment:
     - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672

  selenium:
    container_name: "selenium"
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=10
    volumes:
      - /dev/shm:/dev/shm

  webscrapperservice:
    container_name: "webscrapperservice"
    image: ${DOCKER_REGISTRY-}webscrapperservice
    restart: on-failure:always
    build:
        context: .
        dockerfile: WebScrapper/Dockerfile
    depends_on:
      - rabbitmq
      - selenium
    environment:
      - IsSeleniumOnDocker=true
      - RemoteDriverUri=http://host.docker.internal:4444/wd/hub
      - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672

  joboffersmapperserivce:
    container_name: "joboffersmapperservice"
    image: ${DOCKER_REGISTRY}joboffersmapperservice
    restart: on-failure:always
    build:
        context: .
        dockerfile: JobOffersMapperService/Dockerfile
    depends_on:
     - rabbitmq
    environment:
    - RabbitConnectionUri=amqp://RabbitUser:RabbitPassword@host.docker.internal:5672